substitutions:
  name: coffee-station
  friendly_name: Coffee Station
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
  project:
    name: esphome.web
    version: dev
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
psram:
  mode: octal
  speed: 80MHz
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Nimp7qKh+AT59SYsvAo+dbx7BjQ7jvG13gWZLgmB97Q="

ota:
  - platform: esphome
    password: "bbeaa6501035b059efc793e441145cec"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Coffee-Station Fallback Hotspot"
    password: "S9DyOPklzwi4"

captive_portal:

output:
  - platform: ledc
    pin: 10 #used to be 2
    inverted: True
    frequency: 1220
    id: gpio_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: ${friendly_name} Display Backlight
    id: back_light
    restore_mode: ALWAYS_ON    
debug:
  update_interval: 5s

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32s3.yaml@main
  import_full_config: true

display:
  - platform: rpi_dpi_rgb
    id: main_display
    color_order: RGB
    invert_colors: True
    update_interval: never
    auto_clear_enabled: false # takes 2.8 seconds to clear the display
    dimensions:
      width: 800
      height: 480
    de_pin: 40
    hsync_pin: 39
    vsync_pin: 41
    pclk_pin: 42
    pclk_frequency: 16MHz
    #
    hsync_front_porch: 40
    hsync_pulse_width: 48
    hsync_back_porch: 28
    vsync_front_porch: 13
    vsync_pulse_width: 3
    vsync_back_porch: 45
    #
    data_pins:
      red:
        - 45        #r1
        - 48        #r2
        - 47        #r3
        - 21        #r4
        - 14        #r5
      green:
        - 5         #g0
        - 6         #g1
        - 7         #g2
        - 15        #g3
        - 16        #g4
        - 4         #g5
      blue:
        - 8         #b1
        - 3         #b2
        - 46        #b3
        - 9         #b4
        - 1         #b5

i2c:
  sda: GPIO17
  scl: GPIO18
  scan: true

touchscreen:
  platform: gt911
  #reset_pin:

  # Include Material Design Icons font
  # Thanks to https://community.home-assistant.io/t/display-materialdesign-icons-on-esphome-attached-to-screen/199790/16
font:
  - file: "gfonts://Roboto"
    id: roboto10
    size: 10
    bpp: 4
  - file: "gfonts://Inter@900"
    id: big
    size: 120
  - file: "gfonts://Inter@900"
    id: medium
    size: 60
  - file: "gfonts://Inter@700"
    id: small
    size: 30
  - file: "gfonts://Inter@700"
    id: tiny
    size: 24
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_large
    size: 150
    glyphs: &mdi-weather-glyphs
      - "\U000F0590" # mdi-weather-cloudy
      - "\U000F0F2F" # mdi-weather-cloudy-alert
      - "\U000F0E6E" # mdi-weather-cloudy-arrow-right
      - "\U000F0591" # mdi-weather-fog
      - "\U000F0592" # mdi-weather-hail
      - "\U000F0F30" # mdi-weather-hazy
      - "\U000F0898" # mdi-weather-hurricane
      - "\U000F0593" # mdi-weather-lightning
      - "\U000F067E" # mdi-weather-lightning-rainy
      - "\U000F0594" # mdi-weather-clear-night
      - "\U000F0F31" # mdi-weather-night-partly-cloudy
      - "\U000F0595" # mdi-weather-partly-cloudy
      - "\U000F0F32" # mdi-weather-partly-lightning
      - "\U000F0F33" # mdi-weather-partly-rainy
      - "\U000F0F34" # mdi-weather-partly-snowy
      - "\U000F0F35" # mdi-weather-partly-snowy-rainy
      - "\U000F0596" # mdi-weather-pouring
      - "\U000F0597" # mdi-weather-rainy
      - "\U000F0598" # mdi-weather-snowy
      - "\U000F0F36" # mdi-weather-snowy-heavy
      - "\U000F067F" # mdi-weather-snowy-rainy
      - "\U000F0599" # mdi-weather-sunny
      - "\U000F0F37" # mdi-weather-sunny-alert
      - "\U000F14E4" # mdi-weather-sunny-off
      - "\U000F059A" # mdi-weather-sunset
      - "\U000F059B" # mdi-weather-sunset-down
      - "\U000F059C" # mdi-weather-sunset-up
      - "\U000F0F38" # mdi-weather-tornado
      - "\U000F059D" # mdi-weather-windy
      - "\U000F059E" # mdi-weather-windy-variant
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_medium
    size: 40
    glyphs: *mdi-weather-glyphs

lvgl:
  color_depth: 16
  #log_level: TRACE
  bg_color: 0
  border_width: 0
  outline_width: 0
  shadow_width: 0
  text_font: unscii_16
  align: center
  pages:
    - id: main_page
      widgets:
        - obj:
            align: CENTER
            height: 170
            width: 320
            bg_color: 0x000000
            scrollbar_mode: "OFF"
            #border_width: 0
            #outline_width: 0
            #shadow_width: 0
            pad_all: 0
            widgets:
              - obj:
                  id: weather_icon_obj
                  x: -1
                  y: -1
                  scrollbar_mode: "OFF"
                  #align: LEFT_MID
                  height: 170
                  width: 150
                  bg_color: 0x000000
                  widgets:
                    - label:
                        id: current_weather_icon
                        recolor: true
                        align: CENTER
                        text_font: font_mdi_large
                        text_color: 0xFFFF00
                        text_align: CENTER
                        text: "I"
                        width: 150
              - obj:
                  id: weather_details_obj
                  #x: -1
                  #y: -1
                  scrollbar_mode: "OFF"
                  #align: LEFT_MID
                  align_to:
                      id: weather_icon_obj
                      align: OUT_RIGHT_MID
                  height: 170
                  width: 170
                  bg_color: 0x000000
                  widgets:
                    - label:
                        id: current_date
                        align: LEFT_MID
                        align_to:
                          id: current_time
                          align: OUT_TOP_MID
                        text_font: montserrat_24
                        text_color: 0xFFFF00
                        text_align: LEFT
                        text: "Date"
                        width: 170
                    - label:
                        id: current_time
                        align: LEFT_MID
                        text_font: montserrat_24
                        text_color: 0xFFFF00
                        text_align: LEFT
                        text: "Time"
                        width: 170
                    - label:
                        id: current_temp
                        align: LEFT_MID
                        align_to:
                            id: current_time
                            align: OUT_BOTTOM_MID
                        text_font: montserrat_24
                        text_color: 0xFFFF00
                        text_align: LEFT
                        text: "Temp"
                        width: 170


time:
  - platform: homeassistant
    id: time_comp
    on_time:
      - seconds: 0
        minutes: '*'
        then:
          - lvgl.label.update:
              id: current_time
              text:
                time_format: "%I : %M %p"
                time: !lambda return id(time_comp).now();
          - lvgl.label.update:
              id: current_date
              text:
                time_format: "%a, %b %e"
                time: !lambda return id(time_comp).now();
          #- script.execute: weather_update
    on_time_sync:
        then:
          - lvgl.label.update:
              id: current_time
              text:
                time_format: "%I : %M %p"
                time: !lambda return id(time_comp).now();
          - lvgl.label.update:
              id: current_date
              text:
                time_format: "%a, %b %e"
                time: !lambda return id(time_comp).now();
          #- script.execute: weather_update 
